### ISSUE TITLE
Get Image Characters and Get Image Tags

### ISSUE THREAD

**Issue by generalvamp** [Nekos-API/Nekos-API#18]
Hello, first off thanks for making this API.

I made a go wrapper for this, but seem to be getting Server Error (500) for the following endpoints so was not able to implement these:

* Get an Image's Characters: e.g., https://api.nekosapi.com/v3/images/1449/characters
* Get an Image's Tags: e.g., https://api.nekosapi.com/v3/images/1/tags

Are these endpoints no longer meant to be used? Or am i maybe missing something?

**Comment by Nekidev** [comment]
Hi! Yeah, those endpoints have been failing for a while. I'm currently working on rewriting the API from scratch since it's been super slow lately so I'm not sure if those endpoints will be fixed for now as I want to focus on writing a better version instead. I think that error is because of internal validation of the response before sending it, so it shouldn't be something too difficult to fix. I'll check it out when I'm back home.
