### ISSUE TITLE
Feedback for “Relationships”

### ISSUE THREAD

**Issue by MehmetCanWT** [Nekos-API/Nekos-API#7]
hi i get sucsess json output

but i cant read file 
and i cant put my website

![image](https://github.com/Nekos-API/Nekos-API/assets/52177084/60884ad6-eb14-479c-9dde-f049e2ce8de3)

![image](https://github.com/Nekos-API/Nekos-API/assets/52177084/b302e2e9-13c0-47e1-a42b-56e541eb9c93)

**Comment by Nekidev** [comment]
Hi! Notice that the responses return a top-level `data` object. This means that if `data` is your response's json variable, then it'd be `data.data`.

```js
const res = await fetch(...);
const body = await res.json();

console.log(body.attributes.file);
```

The error you're getting is because you're trying to access an `attributes` property in the top-level object, which only has the `data` and `included` objects.

**Comment by MehmetCanWT** [comment]
thank you
