### ISSUE TITLE
Parameters

### ISSUE THREAD

**Issue by MehmetCanWT** [Nekos-API/Nekos-API#8]
How can i use parameter

https://api.nekosapi.com/v2/images/random/file

in this url

like this?

https://api.nekosapi.com/v2/images/random/file?filter[ageRating]

**Comment by Nekidev** [comment]
Yes, exactly like that. Filters are query parameters following this format: `filter[fieldName.lookupMethod]=value`.

The `lookupMethod` specifies the way in which the filtering is done. For example, `filter[ageRating.exact]=sfw` will only return images marked as SFW. This part of the filter can usually be ignored, it'll probably be `exact` by default if it is not specified.

All in all, `https://api.nekosapi.com/v2/images/random/file?filter[ageRating]=sfw` would redirect to an image file marked as SFW.

Also, make sure to URL encode the `[` and the `]` characters. Usually nothing happens if you don't but you still should.
