### ISSUE TITLE
API 3rd version returning "Server error"

### ISSUE THREAD

**Issue by SharonnElfride** [Nekos-API/Nekos-API#9]
Hello!

I wanted to check the news on the api and saw that I should use the 3rd version and that the 2nd version (that I was using) was going to be discontinued. 

I tried but I keep getting this error:

![image](https://github.com/Nekos-API/Nekos-API/assets/123483236/7693f31c-8a22-479e-ad15-bb1dbabd4677)

Am I using it the wrong way ?

**Comment by Nekidev** [comment]
Yeah, sorry. The API internally validates the responses before sending them to ensure that nothing that is not specified in the [openapi schema](https://api.nekosapi.com/v3/openapi.json). Since the migration from v2 to v3 hasn't been completed yet, some images have null values not specified in the schema which causes that error to be randomly raised (depending on whether the image randomly selected has been processed yet or not). It'll eventually stop returning 500 errors when all images are finally processed. Until then you should retry the request until you get a 200 response.

Thank you for creating an issue for this, I should have put this somewhere before.

**Comment by SharonnElfride** [comment]
> Yeah, sorry. The API internally validates the responses before sending them to ensure that nothing that is not specified in the [openapi schema](https://api.nekosapi.com/v3/openapi.json). Since the migration from v2 to v3 hasn't been completed yet, some images have null values not specified in the schema which causes that error to be randomly raised (depending on whether the image randomly selected has been processed yet or not). It'll eventually stop returning 500 errors when all images are finally processed. Until then you should retry the request until you get a 200 response.
> 
> Thank you for creating an issue for this, I should have put this somewhere before.

Oh I understand. Thank you for your hard work ^^

**Comment by Nekidev** [comment]
I believe there are no more errors caused by this issue so I'll mark this as completed.
